In [5]:
import pandas as pd
import numpy as np

In [9]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [10]:
df = pd.read_csv("covid_toy.csv")

In [11]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [12]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(df.drop(columns= ['has_covid']),df['has_covid'],test_size= 0.2)

In [14]:
x_train

    age  gender  fever   cough       city
81   65    Male   99.0    Mild      Delhi
29   34  Female    NaN  Strong     Mumbai
55   81  Female  101.0    Mild     Mumbai
51   11  Female  100.0  Strong    Kolkata
17   40  Female   98.0  Strong      Delhi
..  ...     ...    ...     ...        ...
23   80  Female   98.0    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
98    5  Female   98.0  Strong     Mumbai
80   14  Female   99.0    Mild     Mumbai
41   82    Male    NaN    Mild    Kolkata

[80 rows x 5 columns]

# 1 Aam zindagi

In [15]:
si = SimpleImputer()

# fit on train, transform train
x_train_fever = si.fit_transform(x_train[['fever']])

# only transform test data, using stats learned from train
x_test_fever = si.transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [16]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

# fit on train, transform train
x_train_cough = oe.fit_transform(x_train[['cough']])

# only transform test data, using categories learned from train
x_test_cough = oe.transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [18]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

# fit on train, transform train
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

# only transform test data, using categories learned from train
x_test_gender_city = ohe.transform(x_test[['gender', 'city']])

x_train_gender_city.shape

(80, 4)

In [20]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [21]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

(80, 7)

# Mentos Zindagi

In [23]:
from sklearn.compose import ColumnTransformer

In [25]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [27]:
transformer.fit_transform(x_train).shape

(80, 7)

In [28]:
transformer.transform(x_test).shape

(20, 7)